# Generated by Django 5.1.4 on 2026-03-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('technical_skills', models.JSONField(default=dict)),
                ('skill_gaps', models.JSONField(default=list)),
                ('project_recommendations', models.JSONField(default=list)),
                ('resume_feedback', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('raw_ai_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='github_analyzer.githubprofile')),
            ],
        ),
    ]
