# Generated by Django 5.1.4 on 2026-03-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('blog', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('public_repos', models.IntegerField(default=0)),
                ('public_gists', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('created_at_github', models.DateTimeField(blank=True, null=True)),
                ('updated_at_github', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('html_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_fork', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('stargazers_count', models.IntegerField(default=0)),
                ('watchers_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('created_at_github', models.DateTimeField(blank=True, null=True)),
                ('updated_at_github', models.DateTimeField(blank=True, null=True)),
                ('pushed_at_github', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
    ]
